### ISSUE TITLE
Not aligned Perfectly

### ISSUE THREAD

**Issue by MJUrian-Learner** [flixlix/shadcn-date-picker#1]
Tried using it in my next js project. The Caption is not perfectly aligned

![Uploading image.png…]()

**Comment by flixlix** [comment]
hey @MJUrian-Learner can you upload the image again? I can't view it

**Comment by MJUrian-Learner** [comment]
> hey @MJUrian-Learner can you upload the image again? I can't view it

When using mobile, the date picker label is mot aligned with the buttons

![image](https://github.com/user-attachments/assets/cf7407b2-33b4-4f4c-8ccb-bab5c0cf8f4f)

**Comment by flixlix** [comment]
thank you @MJUrian-Learner, I fixed this on #2
